spring:
  application:
    name: money-spread
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kakaopay;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update